<a href="https://colab.research.google.com/github/Oleksy1121/Machine-Learning/blob/main/ds/IntroToNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

Podstawy

In [ ]:
import numpy as np
np.__version__

'1.25.2'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [ ]:
x= np.array([1,2,3])
x

array([1, 2, 3])

In [ ]:
print(x)

[1 2 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(3,)

In [ ]:
x.size

3

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.3,2.3,1.4])
print(x)

[1.3 2.3 1.4]


In [ ]:
x.dtype

dtype('float64')

2D Array

In [ ]:
x = np.array([[2,2], [-3,1], [5,2]])
print(x)

[[ 2  2]
 [-3  1]
 [ 5  2]]


In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([[1,2,3], [3,4,5]])
x

array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
x.shape

(2, 3)


3D


In [ ]:
x=np.array(      # można powiedzieć że nawiasy kwadratowe interpretują wymiar tj [[]] = 2 wymiar, [[[]]] = 3 wymiar itd
    [[[4,3,1],
      [3,1,2]],

    [[4,1,3],
     [4,2,1]],

    [[4,5,6],
     [2,3,4]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[4, 5, 6],
        [2, 3, 4]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape   # 3 tablice, 2 wiersze, 3 kolumny


(3, 2, 3)

Tekst

In [ ]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [ ]:
A=np.array([1.0,2.0,3.0],dtype='int')
A.dtype

dtype('int64')

In [ ]:
A=np.array([1,2,3], dtype='complex')
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
A.dtype

dtype('int64')

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A=np.array([24,120,230], dtype=np.int8)
A.dtype

<ipython-input-48-823611e94561>:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 230 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  A=np.array([24,120,230], dtype=np.int8)


dtype('int8')

In [ ]:
A=np.array([24,120,230], dtype=np.uint8)
A.dtype

dtype('uint8')

Tworzenie tablic

In [ ]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(4,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3,3), fill_value=4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [ ]:
np.arange(start=100, stop=10, step=-5)

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25,  20,  15])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Postawowe operacje na tablicach

In [ ]:
A = np.array([1,2,3,4])
B=np.array([5,-6,7,8])
print(A)
print(B)

[1 2 3 4]
[ 5 -6  7  8]


In [ ]:
A+B

array([ 6, -4, 10, 12])

In [ ]:
np.add(A,B)

array([ 6, -4, 10, 12])

In [ ]:
A-B

array([-4,  8, -4, -4])

In [ ]:
np.subtract(A,B)

array([-4,  8, -4, -4])

In [ ]:
A*B

array([  5, -12,  21,  32])

In [ ]:
np.multiply(A,B)

array([  5, -12,  21,  32])

In [ ]:
A/B

array([ 0.2       , -0.33333333,  0.42857143,  0.5       ])

In [ ]:
np.divide(A,B)

array([ 0.2       , -0.33333333,  0.42857143,  0.5       ])

In [ ]:
A+3

array([4, 5, 6, 7])

In [ ]:
A-3

array([-2, -1,  0,  1])

In [ ]:
2*A

array([2, 4, 6, 8])

In [ ]:
A+3*B

array([ 16, -16,  24,  28])

In [ ]:
print(B)
np.abs(B)

[ 5 -6  7  8]


array([5, 6, 7, 8])

In [ ]:
X = np.array([[1,3], [-2,0]])
Y = np.array([[6,0], [-1,2]])

print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [ ]:
X*Y

array([[6, 0],
       [2, 0]])

In [ ]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [ ]:
X @ Y

array([[  3,   6],
       [-12,   0]])

In [ ]:
Y @ X

array([[ 6, 18],
       [-5, -3]])

Generowanie liczb pseudolosowych

In [ ]:
np.random.seed(0)

In [ ]:
np.random.randn()

2.240893199201458

In [ ]:
np.random.randn(10) ## losowa wartość z rozkładu normalnego

array([ 1.86755799, -0.97727788,  0.95008842, -0.15135721, -0.10321885,
        0.4105985 ,  0.14404357,  1.45427351,  0.76103773,  0.12167502])

In [ ]:
np.random.randn(10,4)

array([[ 0.44386323,  0.33367433,  1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574, -2.55298982,  0.6536186 ],
       [ 0.8644362 , -0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,  1.20237985],
       [-0.38732682, -0.30230275, -1.04855297, -1.42001794],
       [-1.70627019,  1.9507754 , -0.50965218, -0.4380743 ],
       [-1.25279536,  0.77749036, -1.61389785, -0.21274028],
       [-0.89546656,  0.3869025 , -0.51080514, -1.18063218]])

In [ ]:
np.random.rand() # losowa wartość z przedziału 0 - 1

0.09710127579306127

In [ ]:
np.random.rand(10)

array([0.83794491, 0.09609841, 0.97645947, 0.4686512 , 0.97676109,
       0.60484552, 0.73926358, 0.03918779, 0.28280696, 0.12019656])

In [ ]:
np.random.rand(10,4)

array([[0.2961402 , 0.11872772, 0.31798318, 0.41426299],
       [0.0641475 , 0.69247212, 0.56660145, 0.26538949],
       [0.52324805, 0.09394051, 0.5759465 , 0.9292962 ],
       [0.31856895, 0.66741038, 0.13179786, 0.7163272 ],
       [0.28940609, 0.18319136, 0.58651293, 0.02010755],
       [0.82894003, 0.00469548, 0.67781654, 0.27000797],
       [0.73519402, 0.96218855, 0.24875314, 0.57615733],
       [0.59204193, 0.57225191, 0.22308163, 0.95274901],
       [0.44712538, 0.84640867, 0.69947928, 0.29743695],
       [0.81379782, 0.39650574, 0.8811032 , 0.58127287]])

In [ ]:
np.random.randint(10) # zwraca cyfrę od 0 do X (w tym przypadku do 10)

9

In [ ]:
np.random.randint(low=10, high=101)

70

In [ ]:
np.random.randint(low=10, high=101, size=10)

array([71, 93, 43, 42, 80, 95, 41, 23, 81, 66])

In [ ]:
np.random.choice([4,1,2,5]) # zwraca losową wartość z listy

5

In [ ]:
np.random.choice(['ptyhon', 'java', 'sgq'])

'sgq'

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)
data

array([4, 2, 1, 8, 3, 0, 6, 7, 5, 9])

Podstawowe funkcje NumPy

In [ ]:
np.exp(1) #eksponent

2.718281828459045

In [ ]:
np.sqrt(4)

2.0